version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: domino
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data